### ISSUE TITLE
`M-y` like emacs?

### ISSUE THREAD

**Issue by mbforbes** [aki77/atom-clipboard-plus#11]
Hi,

First, thank you for making emacs-plus and this package! I use them for hours every day.

My feature request: could `M-y` in this app behave like emacs? In emacs, the behavior of pressing `M-y` repeatedly is to cycle through the kill ring, replacing the pasted text with previously yanked things. In the current implementation, it opens the clipboard bar and then starts pasting "¥" (on OSX).

(Warning: I don't know proper emacs terminology, so the above might sound fishy.)

The reason: there's this workflow that you get into the habit of with emacs where you paste something with `C-y` and then if it's not what you want, you just keep pressing `M-y` again to replace what you pasted with previous text. You keep doing this until you find what you want. It's really convenient, and I miss it dearly!

It seems like binding `M-y` to a command that cycles wouldn't be hard, but I'm not sure if replacing the pasted text with the next item in the clipboard would be messy. I certainly understand if you'd rather not implement this, but I thought I'd ask.

Many thanks and kind regards,
Max

**Comment by aki77** [comment]
Thank you for giving me your good suggestion.
Just try [clip-history](https://atom.io/packages/clip-history), if you like the same behavior of emacs.

**Comment by mbforbes** [comment]
Oh wow! Sorry I missed that. Many thanks for the speedy reply!
