### ISSUE TITLE
Vim-mode paste

### ISSUE THREAD

**Issue by dsandstrom** [aki77/atom-clipboard-plus#2]
Proposed keymaps for Readme:

``` cson
'.platform-darwin atom-text-editor.vim-mode:not(.insert-mode)':
  'ctrl-p': 'clipboard-plus:toggle'

'.platform-linux atom-text-editor.vim-mode:not(.insert-mode)':
  'alt-p': 'clipboard-plus:toggle'
```

However, the clipboard entry shows up on the same line, instead of the next line like a normal vim-mode paste.

Edit. Works fine if you yank or paste from the first character.

**Comment by aki77** [comment]
I implemented a [vim-mode-clipboard-plus package](https://atom.io/packages/vim-mode-clipboard-plus).

**Comment by dsandstrom** [comment]
Awesome.  Much appreciated.

**Comment by aki77** [comment]
:smiley:
