### ISSUE TITLE
Keymaps

### ISSUE THREAD

**Issue by josh-egan** [aki77/atom-clipboard-plus#4]
Is there a reason why you haven't included the clipboard-plus:toggle keyboard shortcuts in the keymaps file? https://github.com/aki77/atom-clipboard-plus/blob/master/keymaps/clipboard-plus.cson

The below are in the README. Just wondering why you don't have it in this project's keymap file so that it would be implemented be default without having to open and edit my atom keymap file.

```
'.platform-darwin atom-text-editor:not([mini])':
  'cmd-shift-v': 'clipboard-plus:toggle'

'.platform-win32 atom-text-editor:not([mini])':
  'ctrl-shift-v': 'clipboard-plus:toggle'

'.platform-linux atom-text-editor:not([mini])':
  'ctrl-shift-v': 'clipboard-plus:toggle'
```

**Comment by aki77** [comment]
Please see.

https://discuss.atom.io/t/key-binding-hell/12075
