### ISSUE TITLE
Use the delete key to remove history items

### ISSUE THREAD

**Issue by ijanos** [aki77/atom-clipboard-plus#5]
I propose the delete key as a shortcut to delete the selected history item.

**Comment by aki77** [comment]
No sorry.
Delete key is required for mini-editor .

[![Gyazo](https://i.gyazo.com/86ea8e61a4d85415c59ea638c51d767f.gif)](https://gyazo.com/86ea8e61a4d85415c59ea638c51d767f)

**Comment by ijanos** [comment]
I think you are confusing the delete key with backspace. Probably you are using a Mac and as I see from a google image search they don't have a delete key and sometimes they label backspace key as delete. So yeah, I meant "the other" delete key. 

I'm not familiar with atom internals, can I map delete item action to a key in keymap.cson? If yes then I will do that if not then I would like to reopen this ticket. 

Cheers.
