### ISSUE TITLE
text in clipboard widget does not respect font settings, causing non-ascii character displaying problems

### ISSUE THREAD

**Issue by chaserhkj** [aki77/atom-clipboard-plus#6]
As shown below in the screenshot.

![screen](https://cloud.githubusercontent.com/assets/1768423/9573268/e0ac1e4a-4fec-11e5-8f4f-f6f1615a5430.png)

Clipboard widget created by atom-clipboard-plus is not respecting my font setup in atom settings:

config.cson:

``` cson
  editor:
    invisibles: {}
    fontFamily: "Liberation Mono, WenQuanYi Micro Hei Mono"
    softWrap: true
```

And thus non-ascii characters (in my case, Chinese characters) are not rendered correctly, cause default used English font do not have these characters, and Chinese fonts must be used to display them.

**Comment by aki77** [comment]
clipboard-plus did not change the font style.
Japanese fonts are displayed correctly.

[![Gyazo](https://i.gyazo.com/d34b5f0ccdb326f9c5cd9a72f319191e.png)](https://gyazo.com/d34b5f0ccdb326f9c5cd9a72f319191e)

**Comment by chaserhkj** [comment]
After inspection, I found the problem is that all atom-panels in atom is not respecting the font setup in atom settings, and font-family options are just falling back to `bootstrap.css`'s setup, which uses system's default monospace font, and do not have any Chinese glyphs.

@aki77 : I believe that it is because your system's default monospace font has already included all Japanese glyphs that this problem does not occur on your side.

Currently I'm using these lines in `styles.less`, overriding `bootstrap.css` setups as a work-around.

``` less
code,kbd,pre,samp {
  font-family: "Liberation Mono", "WenQuanYi Micro Hei Mono" !important; // Replace with preferred font.
}
```

So this should be considered as an atom issue, I'll consider sending an issue to atom repository then.

**Comment by aki77** [comment]
Thank you for reporting. :smiley:

**Comment by chaserhkj** [comment]
Reported to atom repository as atom/atom#8590
